```typescript
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';
import { baseURL } from './src/config';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables based on NODE_ENV
dotenv.config({ path: `.env.${process.env.NODE_ENV || 'test'}` });

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
    testDir: './tests',
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!process.env.CI,
    /* Retry on CI only */
    retries: process.env.CI ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : undefined,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: [
        ['list'],
        ['html', { outputFolder: 'reports/html', open: 'never' }],
        ['json', { outputFile: 'reports/json/results.json' }],
        // Allure reporter for detailed, interactive reports
        ['allure-playwright', { outputFolder: 'reports/allure-results', testMode: false }],
    ],
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        /* Base URL to use in actions like `await page.goto('/')`. */
        baseURL: baseURL,
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
        /* Capture screenshot on failure */
        screenshot: 'only-on-failure',
        /* Define storage state path for authentication persistence */
        storageState: path.join(__dirname, 'playwright/.auth/user.json'),
    },

    /* Configure projects for major browsers */
    projects: [
        // Setup project for authentication, runs once before all other tests
        {
            name: 'setup',
            testMatch: /playwright-framework\/auth\.setup\.ts/,
            // No teardown needed directly for auth setup, but can be added if cleanup is required.
        },
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                // Use the auth state generated by the 'setup' project
                storageState: path.join(__dirname, 'playwright/.auth/user.json'),
            },
            dependencies: ['setup'], // Ensure 'setup' project runs first
            testDir: './tests/e2e', // Only run E2E tests for browser projects
        },
        {
            name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
                storageState: path.join(__dirname, 'playwright/.auth/user.json'),
            },
            dependencies: ['setup'],
            testDir: './tests/e2e',
        },
        {
            name: 'webkit',
            use: {
                ...devices['Desktop Safari'],
                storageState: path.join(__dirname, 'playwright/.auth/user.json'),
            },
            dependencies: ['setup'],
            testDir: './tests/e2e',
        },
        /* API tests project - typically doesn't need UI-based auth state */
        {
            name: 'api',
            testDir: './tests/api',
            use: {
                // Can have its own API base URL or reuse the main baseURL
                baseURL: process.env.API_BASE_URL || baseURL,
            },
        },
    ],

    /* Run your local dev server before starting the tests */
    // webServer: {
    //   command: 'npm run start',
    //   url: 'http://127.0.0.1:3000',
    //   reuseExistingServer: !process.env.CI,
    // },
});

```

```typescript
// playwright-framework/auth.setup.ts
import { test as setup, expect } from '@playwright/test';
import { baseURL } from '../src/config';
import { PageManager } from '../src/pages/PageManager';
import users from '../src/test-data/users.json';
import path from 'path';

// Define the path for the authentication state file
const authFile = path.join(__dirname, '..', 'playwright/.auth/user.json');

/**
 * This setup script handles the authentication process for a 'salesman' user.
 * It logs in the user and saves their authentication state (cookies, local storage, etc.)
 * to a file, which can then be reused by subsequent tests to avoid repeated logins.
 */
setup('authenticate as salesman', async ({ page }) => {
    const pageManager = new PageManager(page);
    const salesmanUser = users.salesman; // Get salesman credentials from test-data

    // 1. Navigate to the login page
    await page.goto(baseURL + '/login');
    await page.waitForLoadState('domcontentloaded'); // Ensure page is loaded

    // 2. Perform login using the LoginPage Page Object
    await test.step('Perform Salesman Login', async () => {
        await expect(pageManager.loginPage.usernameInput).toBeVisible(); // Assert login page loaded
        await pageManager.loginPage.login(salesmanUser.username, salesmanUser.password);
    });

    // 3. Wait for post-login redirection and assert success
    await test.step('Verify Post-Login State', async () => {
        // Wait for URL to change to the expected dashboard or home page after successful login
        await page.waitForURL(baseURL + '/dashboard', { waitUntil: 'networkidle' });
        // Assert a visible element indicating successful login, e.g., a welcome message or dashboard element
        await expect(page.locator('h1', { hasText: 'Dashboard' }).or(page.getByText(`Welcome, ${salesmanUser.username.split('@')[0]}`))).toBeVisible();
    });

    // 4. Save the authentication state
    // This will save cookies, local storage, and session storage to the specified file.
    await page.context().storageState({ path: authFile });
    console.log(`Authentication state saved to: ${authFile}`);
});

```

```typescript
// src/config/environments/qa.config.ts
const qaConfig = {
    baseURL: process.env.APP_BASE_URL || 'https://retailer-portal.qa.example.com', // Replace with actual QA application base URL
    apiBaseURL: process.env.API_BASE_URL || 'https://retailer-api.qa.example.com/v1', // Replace with actual QA API base URL
    // Add other QA-specific configuration settings here
    timeout: 30000, // Example timeout
};

export default qaConfig;

```

```typescript
// src/config/index.ts
import devConfig from './environments/dev.config';
import qaConfig from './environments/qa.config';

/**
 * Defines the structure for application configuration.
 */
interface AppConfig {
    baseURL: string;
    apiBaseURL: string;
    timeout: number;
    // Add other global config properties as needed
}

let config: AppConfig;

// Determine the environment and load the corresponding configuration.
// Default to 'qa' if NODE_ENV is not set or not recognized.
switch (process.env.NODE_ENV) {
    case 'development':
        config = devConfig;
        break;
    case 'qa':
    case 'test': // Playwright often runs in a 'test' environment by default
    default:
        config = qaConfig;
        break;
}

// Export specific configuration properties for easy access throughout the framework
export const { baseURL, apiBaseURL, timeout } = config;

// Optionally export the full config object if needed
export default config;

```

```typescript
// src/fixtures/base.fixture.ts
import { test as baseTest } from '@playwright/test';
import { PageManager } from '../pages/PageManager'; // Adjust path as necessary

/**
 * Define custom fixtures that extend Playwright's base `test` object.
 * This allows us to inject custom objects like `pageManager` into our tests.
 */
type MyFixtures = {
    pageManager: PageManager; // Custom fixture for Page Object Manager
};

export const test = baseTest.extend<MyFixtures>({
    // pageManager fixture: initializes and provides a PageManager instance
    pageManager: async ({ page }, use) => {
        const pm = new PageManager(page);
        await use(pm); // Provide the PageManager instance to the test
    },
});

// Re-export Playwright's expect for convenience
export { expect } from '@playwright/test';

```

```typescript
// src/pages/auth/LoginPage.ts
import { Page, Locator } from '@playwright/test';
import { baseURL } from '../../config'; // Import base URL from config

/**
 * Represents the Login Page of the application using the Page Object Model.
 * Encapsulates selectors and actions related to the login functionality.
 */
export class LoginPage {
    private readonly page: Page; // Playwright Page object
    readonly usernameInput: Locator;
    readonly passwordInput: Locator;
    readonly loginButton: Locator;
    readonly errorMessage: Locator;

    /**
     * Constructor for LoginPage.
     * @param page The Playwright Page object.
     */
    constructor(page: Page) {
        this.page = page;
        this.usernameInput = page.getByLabel('Username').or(page.locator('#username')).or(page.locator('[name="username"]'));
        this.passwordInput = page.getByLabel('Password').or(page.locator('#password')).or(page.locator('[name="password"]'));
        this.loginButton = page.getByRole('button', { name: 'Login' }).or(page.locator('input[type="submit"]'));
        this.errorMessage = page.locator('[data-testid="login-error"]').or(page.getByText('Invalid credentials.'));
    }

    /**
     * Navigates to the login page.
     */
    async navigate(): Promise<void> {
        await this.page.goto(`${baseURL}/login`);
        await this.page.waitForLoadState('domcontentloaded');
    }

    /**
     * Performs a login action with the given credentials.
     * @param username The username to enter.
     * @param password The password to enter.
     */
    async login(username: string, password: string): Promise<void> {
        await this.usernameInput.fill(username);
        await this.passwordInput.fill(password);
        await this.loginButton.click();
    }

    /**
     * Asserts that an error message is visible after a failed login attempt.
     * @param message Optional. The expected text content of the error message.
     */
    async verifyErrorMessageVisible(message?: string): Promise<void> {
        await expect(this.errorMessage).toBeVisible();
        if (message) {
            await expect(this.errorMessage).toContainText(message);
        }
    }
}

```

```typescript
// src/pages/common/HeaderComponent.ts
import { Page, Locator } from '@playwright/test';

/**
 * Represents the common header component present on most pages of the application.
 * Encapsulates selectors and actions related to header navigation and common elements.
 */
export class HeaderComponent {
    private readonly page: Page;
    readonly retailerLink: Locator;
    readonly createNewRetailerButton: Locator; // Can be a button or a link in a menu
    readonly profileDropdown: Locator;
    readonly logoutButton: Locator;

    /**
     * Constructor for HeaderComponent.
     * @param page The Playwright Page object.
     */
    constructor(page: Page) {
        this.page = page;
        this.retailerLink = page.getByRole('link', { name: 'Retailers', exact: true }).or(page.locator('[data-testid="nav-retailers"]'));
        this.createNewRetailerButton = page.getByRole('button', { name: 'Create New Retailer' }).or(page.getByRole('link', { name: 'New Retailer' })).or(page.locator('[data-testid="create-retailer-btn"]'));
        this.profileDropdown = page.locator('#user-profile-dropdown').or(page.locator('[data-testid="profile-dropdown-toggle"]'));
        this.logoutButton = page.getByRole('button', { name: 'Logout' }).or(page.getByRole('link', { name: 'Logout' }));
    }

    /**
     * Clicks the "Retailers" navigation link.
     */
    async clickRetailersLink(): Promise<void> {
        await this.retailerLink.click();
        await this.page.waitForLoadState('networkidle'); // Wait for navigation to complete
    }

    /**
     * Clicks the "Create New Retailer" button/link.
     * Assumes it's directly accessible from the header or a simple navigation menu.
     */
    async clickCreateNewRetailer(): Promise<void> {
        await this.createNewRetailerButton.click();
        await this.page.waitForLoadState('networkidle'); // Wait for page navigation
    }

    /**
     * Opens the profile dropdown and clicks the logout button.
     */
    async logout(): Promise<void> {
        await this.profileDropdown.click();
        await this.logoutButton.click();
        await this.page.waitForURL(/.*\/login/); // Assume logout redirects to login page
    }
}
```

```typescript
// src/pages/retailers/CreateRetailerPage.ts
import { Page, Locator, expect } from '@playwright/test';
import { RetailerData } from '../../test-data/retailers/newRetailer'; // Assuming type for test data
import { baseURL } from '../../config'; // Import base URL

/**
 * Represents the 'Create Retailer' page using the Page Object Model.
 * Encapsulates selectors and actions for interacting with the retailer creation form.
 */
export class CreateRetailerPage {
    private readonly page: Page;
    readonly pageTitle: Locator;
    readonly retailerNameInput: Locator;
    readonly retailerCodeInput: Locator;
    readonly emailInput: Locator;
    readonly phoneInput: Locator;
    readonly address1Input: Locator;
    readonly cityInput: Locator;
    readonly stateSelect: Locator; // Assuming a select dropdown or autocomplete
    readonly zipInput: Locator;
    readonly countrySelect: Locator; // Assuming a select dropdown
    readonly submitButton: Locator;
    readonly cancelButton: Locator;
    readonly successMessage: Locator;
    readonly errorMessage: Locator; // Generic error message for form submission
    readonly retailerNameError: Locator;
    readonly emailError: Locator;
    readonly retailerCodeError: Locator;


    /**
     * Constructor for CreateRetailerPage.
     * @param page The Playwright Page object.
     */
    constructor(page: Page) {
        this.page = page;
        this.pageTitle = page.locator('h1', { hasText: 'Create New Retailer' });
        this.retailerNameInput = page.getByLabel('Retailer Name', { exact: true }).or(page.locator('#retailerName'));
        this.retailerCodeInput = page.getByLabel('Retailer Code', { exact: true }).or(page.locator('#retailerCode'));
        this.emailInput = page.getByLabel('Email', { exact: true }).or(page.locator('#email'));
        this.phoneInput = page.getByLabel('Phone Number', { exact: true }).or(page.locator('#phoneNumber'));
        this.address1Input = page.getByLabel('Address Line 1', { exact: true }).or(page.locator('#addressLine1'));
        this.cityInput = page.getByLabel('City', { exact: true }).or(page.locator('#city'));
        this.stateSelect = page.getByLabel('State/Province', { exact: true }).or(page.locator('#stateProvince'));
        this.zipInput = page.getByLabel('Zip/Postal Code', { exact: true }).or(page.locator('#zipCode'));
        this.countrySelect = page.getByLabel('Country', { exact: true }).or(page.locator('#country'));
        this.submitButton = page.getByRole('button', { name: 'Create Retailer' }).or(page.locator('[data-testid="submit-create-retailer"]'));
        this.cancelButton = page.getByRole('button', { name: 'Cancel' });

        this.successMessage = page.locator('[data-testid="success-message"]').or(page.getByText('Retailer created successfully!', { exact: true }));
        this.errorMessage = page.locator('[data-testid="error-message"]').or(page.getByText('Failed to create retailer. Please try again.'));

        // Specific field validation error messages (assuming they appear next to the field or have specific IDs)
        this.retailerNameError = page.locator('#retailerName-error').or(page.locator('[aria-labelledby="retailerName"] + .error-message'));
        this.emailError = page.locator('#email-error').or(page.locator('[aria-labelledby="email"] + .error-message'));
        this.retailerCodeError = page.locator('#retailerCode-error').or(page.locator('[aria-labelledby="retailerCode"] + .error-message'));
    }

    /**
     * Navigates directly to the Create Retailer page.
     */
    async navigate(): Promise<void> {
        await this.page.goto(`${baseURL}/retailers/create`);
        await this.page.waitForLoadState('networkidle');
        await expect(this.pageTitle).toBeVisible(); // Ensure page title is visible
    }

    /**
     * Fills in the mandatory details for creating a new retailer.
     * @param retailer The RetailerData object containing details to fill.
     */
    async fillMandatoryDetails(retailer: RetailerData): Promise<void> {
        if (retailer.name) await this.retailerNameInput.fill(retailer.name);
        if (retailer.code) await this.retailerCodeInput.fill(retailer.code);
        if (retailer.email) await this.emailInput.fill(retailer.email);
        if (retailer.phone) await this.phoneInput.fill(retailer.phone);
        if (retailer.address1) await this.address1Input.fill(retailer.address1);
        if (retailer.city) await this.cityInput.fill(retailer.city);
        if (retailer.state) await this.stateSelect.selectOption(retailer.state); // Select by value or label
        if (retailer.zip) await this.zipInput.fill(retailer.zip);
        if (retailer.country) await this.countrySelect.selectOption(retailer.country); // Select by value or label
        await this.page.waitForTimeout(100); // Small delay to ensure all fields are processed by UI framework
    }

    /**
     * Submits the retailer creation form.
     */
    async submitForm(): Promise<void> {
        await this.submitButton.click();
    }

    /**
     * Verifies that a success message is displayed after form submission.
     * @param expectedMessage Optional. The specific text content to check within the success message.
     */
    async verifyRetailerCreationSuccess(expectedMessage?: string): Promise<void> {
        await expect(this.successMessage).toBeVisible();
        if (expectedMessage) {
            await expect(this.successMessage).toContainText(expectedMessage);
        }
    }

    /**
     * Verifies that a generic error message is displayed after form submission.
     * @param expectedMessage Optional. The specific text content to check within the error message.
     */
    async verifyRetailerCreationFailure(expectedMessage?: string): Promise<void> {
        await expect(this.errorMessage).toBeVisible();
        if (expectedMessage) {
            await expect(this.errorMessage).toContainText(expectedMessage);
        }
    }

    /**
     * Verifies that a specific field's error message is visible.
     * @param fieldLocator The locator for the field's error message.
     * @param expectedText The expected text content of the error message.
     */
    async verifyFieldErrorMessage(fieldLocator: Locator, expectedText: string): Promise<void> {
        await expect(fieldLocator).toBeVisible();
        await expect(fieldLocator).toContainText(expectedText);
    }
}
```

```typescript
// src/pages/PageManager.ts
import { Page } from '@playwright/test';
import { LoginPage } from './auth/LoginPage';
import { CreateRetailerPage } from './retailers/CreateRetailerPage';
import { HeaderComponent } from './common/HeaderComponent';

/**
 * PageManager provides a single point of access to all Page Object Model instances.
 * This helps in managing page objects and avoids redundant instantiation across tests.
 */
export class PageManager {
    private readonly page: Page;
    private _loginPage: LoginPage | undefined;
    private _createRetailerPage: CreateRetailerPage | undefined;
    private _headerComponent: HeaderComponent | undefined;
    // Add more page object instances here as they are created

    /**
     * Initializes the PageManager with a Playwright Page instance.
     * @param page The Playwright Page object.
     */
    constructor(page: Page) {
        this.page = page;
    }

    /**
     * Getter for the LoginPage Page Object. Instantiates if not already done.
     */
    get loginPage(): LoginPage {
        if (!this._loginPage) {
            this._loginPage = new LoginPage(this.page);
        }
        return this._loginPage;
    }

    /**
     * Getter for the CreateRetailerPage Page Object. Instantiates if not already done.
     */
    get createRetailerPage(): CreateRetailerPage {
        if (!this._createRetailerPage) {
            this._createRetailerPage = new CreateRetailerPage(this.page);
        }
        return this._createRetailerPage;
    }

    /**
     * Getter for the HeaderComponent Page Object. Instantiates if not already done.
     */
    get headerComponent(): HeaderComponent {
        if (!this._headerComponent) {
            this._headerComponent = new HeaderComponent(this.page);
        }
        return this._headerComponent;
    }

    // Add getters for other page objects here (e.g., get RetailerListPage(): RetailerListPage { ... })
}

```

```typescript
// src/test-data/retailers/newRetailer.ts
import { faker } from '@faker-js/faker';

/**
 * Interface defining the structure for new retailer data.
 */
export interface RetailerData {
    name: string;
    code: string;
    email: string;
    phone: string;
    address1: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    // Add other optional or mandatory fields as per application's form
}

/**
 * Generates realistic and unique data for a new retailer using Faker.js.
 * This ensures test data is fresh for each test run, reducing test flakiness
 * due to data collisions.
 * @returns A RetailerData object with generated details.
 */
export function generateNewRetailerData(): RetailerData {
    const companyName = faker.company.name();
    return {
        name: companyName,
        // Generate a unique code, e.g., first 3 letters of company + random alphanumeric
        code: `${companyName.substring(0, 3).toUpperCase()}-${faker.string.alphanumeric(5).toUpperCase()}`,
        email: faker.internet.email({ provider: `${faker.internet.domainWord()}.com` }),
        phone: faker.phone.number('###-###-####'),
        address1: faker.location.streetAddress(),
        city: faker.location.city(),
        state: faker.location.state({ abbreviated: true }), // e.g., "CA"
        zip: faker.location.zipCode('#####'),
        country: 'United States', // Can be randomized from a list if multiple countries are supported
    };
}

```

```json
// src/test-data/users.json
{
  "salesman": {
    "username": "salesman@example.com",
    "password": "SalesmanPassword123"
  },
  "admin": {
    "username": "admin@example.com",
    "password": "AdminPassword123"
  }
}

```

```typescript
// tests/e2e/retailers/createRetailer.spec.ts
import { test, expect } from '../../../src/fixtures/base.fixture';
import { generateNewRetailerData } from '../../../src/test-data/retailers/newRetailer';
import { baseURL } from '../../../src/config'; // Import base URL from config for direct navigation if needed
import { RetailerData } from '../../../src/test-data/retailers/newRetailer';

// Define a test suite for Retailer Management features
test.describe('Retailer Management E2E Tests: Salesman - Create New Retailer', () => {

    // Runs before each test in this describe block.
    // Assumes the salesman is already logged in due to `auth.setup.ts` and `storageState`.
    // We navigate to a known starting point, like the dashboard, to ensure a consistent state.
    test.beforeEach(async ({ page }) => {
        await page.goto(baseURL + '/dashboard', { waitUntil: 'networkidle' });
        // Optional: Assert that we are on the dashboard or a logged-in state
        await expect(page.locator('h1', { hasText: 'Dashboard' }).or(page.locator('text=Welcome'))).toBeVisible();
    });

    // Test Case: Salesman can successfully create a new retailer with all mandatory details.
    test('TC-RET-001: Salesman can successfully create a new retailer with mandatory details', async ({ page, pageManager }) => {
        const newRetailer: RetailerData = generateNewRetailerData();

        // Add metadata for reporting (e.g., Allure reports)
        test.info().annotations.push({ type: 'User Story', description: 'US-002: Create New Retailer' });
        test.info().annotations.push({ type: 'Test Case ID', description: 'TC-RET-001' });
        test.info().annotations.push({ type: 'Severity', description: 'Critical' });

        await test.step('Navigate to the Create Retailer page', async () => {
            // Use HeaderComponent to navigate or directly navigate if no clear UI path from dashboard
            if (await pageManager.headerComponent.createNewRetailerButton.isVisible()) {
                await pageManager.headerComponent.clickCreateNewRetailer();
            } else {
                // Fallback for direct navigation if button isn't immediately visible or is in a different menu
                await pageManager.createRetailerPage.navigate();
            }
            // Verify that the URL is correct and the form title is visible
            await expect(page).toHaveURL(/.*\/retailers\/create/);
            await expect(pageManager.createRetailerPage.pageTitle).toBeVisible();
        });

        await test.step('Fill in all mandatory retailer details', async () => {
            await pageManager.createRetailerPage.fillMandatoryDetails(newRetailer);
            // Assert that the fields have been filled correctly
            await expect(pageManager.createRetailerPage.retailerNameInput).toHaveValue(newRetailer.name);
            await expect(pageManager.createRetailerPage.emailInput).toHaveValue(newRetailer.email);
            await expect(pageManager.createRetailerPage.retailerCodeInput).toHaveValue(newRetailer.code);
            // Add more assertions for other filled fields if necessary
        });

        await test.step('Submit the create retailer form', async () => {
            await pageManager.createRetailerPage.submitForm();
            // Wait for network activity to settle, indicating form submission processing
            await page.waitForLoadState('networkidle');
        });

        await test.step('Verify successful retailer creation and redirection', async () => {
            // Assert success message is displayed
            await pageManager.createRetailerPage.verifyRetailerCreationSuccess('Retailer created successfully!');

            // Assert redirection to the retailer's detail page or a list page
            // Assuming the URL changes to something like /retailers/{id} or back to a list
            await expect(page).toHaveURL(/.*\/retailers\/\w{8,}/); // Regex for retailer ID in URL
            await expect(page.locator('h1')).toContainText(newRetailer.name, { ignoreCase: true }); // Check if retailer name is displayed on the new page
        });

        await test.step('Verify the newly created retailer appears in the retailer list (Optional)', async () => {
            // Navigate to the retailer list page
            await pageManager.headerComponent.clickRetailersLink();
            await expect(page).toHaveURL(/.*\/retailers/);
            await expect(page.getByRole('heading', { name: 'Retailers List' })).toBeVisible();

            // Search for the newly created retailer by name (assuming a search bar exists)
            const searchInput = page.getByPlaceholder('Search retailers').or(page.getByLabel('Search'));
            if (await searchInput.isVisible()) {
                await searchInput.fill(newRetailer.name);
                await page.waitForTimeout(500); // Small wait for search results to load
            }

            // Assert that the new retailer's name is visible in the list table/grid
            const newRetailerRow = page.locator(`table tr:has-text("${newRetailer.name}")`);
            await expect(newRetailerRow).toBeVisible();
            await expect(newRetailerRow).toContainText(newRetailer.email);
            await expect(newRetailerRow).toContainText(newRetailer.code);
        });
    });

    // Test Case: Salesman cannot create a retailer with missing mandatory details (e.g., empty name).
    test('TC-RET-002: Salesman cannot create a retailer with missing mandatory name', async ({ page, pageManager }) => {
        const newRetailer: RetailerData = generateNewRetailerData();
        const invalidRetailer: RetailerData = { ...newRetailer, name: '' }; // Simulate missing name

        test.info().annotations.push({ type: 'User Story', description: 'US-002: Create New Retailer - Negative' });
        test.info().annotations.push({ type: 'Test Case ID', description: 'TC-RET-002' });
        test.info().annotations.push({ type: 'Requirement', description: 'All mandatory fields must be filled.' });

        await test.step('Navigate to the Create Retailer page', async () => {
            await pageManager.createRetailerPage.navigate();
            await expect(pageManager.createRetailerPage.pageTitle).toBeVisible();
        });

        await test.step('Fill in details, but omit the mandatory "Retailer Name" field', async () => {
            await pageManager.createRetailerPage.fillMandatoryDetails(invalidRetailer);
            // Ensure the name field is actually empty or cleared if it had a default
            await pageManager.createRetailerPage.retailerNameInput.clear();
            await expect(pageManager.createRetailerPage.retailerNameInput).toBeEmpty();
            await expect(pageManager.createRetailerPage.emailInput).toHaveValue(invalidRetailer.email); // Other fields filled correctly
        });

        await test.step('Attempt to submit the form', async () => {
            await pageManager.createRetailerPage.submitForm();
        });

        await test.step('Verify validation error for missing name and no success message', async () => {
            // Expect field-specific error message to be visible
            await pageManager.createRetailerPage.verifyFieldErrorMessage(pageManager.createRetailerPage.retailerNameError, 'Retailer Name is required.');
            // Expect the input field to be marked as invalid (e.g., aria-invalid attribute)
            await expect(pageManager.createRetailerPage.retailerNameInput).toHaveAttribute('aria-invalid', 'true');

            // Ensure no success message appears and the user remains on the form page
            await expect(pageManager.createRetailerPage.successMessage).not.toBeVisible();
            await expect(pageManager.createRetailerPage.submitButton).toBeVisible(); // Form still present
        });
    });

    // Test Case: Salesman cannot create a retailer with an invalid email format.
    test('TC-RET-003: Salesman cannot create a retailer with invalid email format', async ({ page, pageManager }) => {
        const newRetailer: RetailerData = generateNewRetailerData();
        const invalidRetailer: RetailerData = { ...newRetailer, email: 'invalid-email-format' }; // Simulate invalid email

        test.info().annotations.push({ type: 'User Story', description: 'US-002: Create New Retailer - Invalid Input' });
        test.info().annotations.push({ type: 'Test Case ID', description: 'TC-RET-003' });
        test.info().annotations.push({ type: 'Requirement', description: 'Email field must follow a valid format.' });

        await test.step('Navigate to the Create Retailer page', async () => {
            await pageManager.createRetailerPage.navigate();
            await expect(pageManager.createRetailerPage.pageTitle).toBeVisible();
        });

        await test.step('Fill in details with an invalid email format', async () => {
            await pageManager.createRetailerPage.fillMandatoryDetails(invalidRetailer);
            await expect(pageManager.createRetailerPage.emailInput).toHaveValue(invalidRetailer.email);
        });

        await test.step('Attempt to submit the form', async () => {
            await pageManager.createRetailerPage.submitForm();
        });

        await test.step('Verify validation error for invalid email and no success message', async () => {
            await pageManager.createRetailerPage.verifyFieldErrorMessage(pageManager.createRetailerPage.emailError, 'Please enter a valid email address.');
            await expect(pageManager.createRetailerPage.emailInput).toHaveAttribute('aria-invalid', 'true');

            await expect(pageManager.createRetailerPage.successMessage).not.toBeVisible();
            await expect(pageManager.createRetailerPage.submitButton).toBeVisible();
        });
    });

    // Test Case: Salesman cannot create a retailer with a duplicate retailer code.
    test('TC-RET-004: Salesman cannot create a retailer with a duplicate retailer code', async ({ page, pageManager }) => {
        const existingRetailer: RetailerData = generateNewRetailerData();

        // Pre-condition: Create a retailer via UI to ensure a duplicate code exists in the system
        test.info().annotations.push({ type: 'Pre-condition', description: 'Create an initial retailer to simulate duplicate code scenario.' });
        await test.step('Pre-condition: Create an initial retailer to have a duplicate code', async () => {
            await pageManager.createRetailerPage.navigate();
            await pageManager.createRetailerPage.fillMandatoryDetails(existingRetailer);
            await pageManager.createRetailerPage.submitForm();
            await pageManager.createRetailerPage.verifyRetailerCreationSuccess();
            await expect(page).toHaveURL(/.*\/retailers\/\w{8,}/);
            // Navigate back to the create page for the actual test case scenario
            await pageManager.createRetailerPage.navigate();
        });

        const duplicateRetailer: RetailerData = generateNewRetailerData();
        duplicateRetailer.code = existingRetailer.code; // Intentionally use the code from the previously created retailer

        test.info().annotations.push({ type: 'User Story', description: 'US-002: Create New Retailer - Duplicate Data' });
        test.info().annotations.push({ type: 'Test Case ID', description: 'TC-RET-004' });
        test.info().annotations.push({ type: 'Requirement', description: 'Retailer code must be unique.' });

        await test.step('Fill in details with a duplicate retailer code', async () => {
            await pageManager.createRetailerPage.fillMandatoryDetails(duplicateRetailer);
            await expect(pageManager.createRetailerPage.retailerCodeInput).toHaveValue(duplicateRetailer.code);
        });

        await test.step('Attempt to submit the form', async () => {
            await pageManager.createRetailerPage.submitForm();
        });

        await test.step('Verify server-side error message for duplicate retailer code', async () => {
            // Assuming a server-side validation error appears after submission (not client-side)
            await pageManager.createRetailerPage.verifyRetailerCreationFailure('Retailer code already exists. Please use a unique code.');
            // Optionally, check if the specific field is highlighted as invalid by the server response
            // await expect(pageManager.createRetailerPage.retailerCodeError).toBeVisible();
            // await expect(pageManager.createRetailerPage.retailerCodeError).toContainText('Code already exists');
            await expect(pageManager.createRetailerPage.submitButton).toBeVisible(); // Still on the form page
        });
    });

    // Additional test cases can be added here, for example:
    // - TC-RET-005: Salesman can create a retailer with optional fields (if any)
    // - TC-RET-006: Salesman cannot create a retailer with missing mandatory phone number
    // - TC-RET-007: Salesman cannot create a retailer with invalid phone number format
    // - TC-RET-008: Salesman cannot create a retailer without selecting a country (if mandatory)
    // - TC-RET-009: Verify character limits for text fields
});
```